version: '3.6'

networks:
  ansible:
    external: false

services:
  ansible:
    build:
      context: .
      dockerfile: ./docker/ansible/Dockerfile
    volumes:
      - ./docker/ansible/rootfs/opt/ansible:/opt/ansible
      - ./docker/shared/ssh/:/root/.ssh
      - ./docker/ansible/rootfs/etc/ansible/hosts:/etc/ansible/hosts
    entrypoint: bash
    networks:
      - ansible